[build]
command = "npm run pwa:build"
publish = "www"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "no-cache"

[[headers]]
for = "/service-worker.js"

[headers.values]
Cache-Control = "no-cache"
